/**
 * Copyright 2026 Franja (Frank) Povazanj
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Sequence verdict of the G-code pierce path (issue #983), exercised without a
 * controller. Runs in `npm run check:gcode`, so the rules are tested even where
 * grbl-gvalidate is not installed.
 *
 * The positive programs are generated by the exporter itself, and every
 * negative is that same program with one load-bearing line mutated: if a
 * mutation passes, or trips fewer rules than it should, the rule it exists to
 * exercise has stopped working.
 */

import assert from 'node:assert/strict'
import { exportPlasma, PLASMA_EXPORT_SCENARIOS } from '../../../src/test/plasmaExportFixtures'
import { judge, mismatch, parseProgram } from './verdict'
import type { Rule } from './verdict'

const BASE = exportPlasma({ ...PLASMA_EXPORT_SCENARIOS['single-outline'](), machineId: 'grbl-plasma' }).result.gcode
assert.ok(BASE.includes('M3 S1000'), 'the fixture actually fires the torch')

/** The base program with exactly one mutation applied. */
function mutate(pattern: RegExp, replacement: string): string {
  const mutated = BASE.replace(pattern, replacement)
  assert.notEqual(mutated, BASE, `the mutation ${pattern} matched nothing`)
  return mutated
}

// The real exported program passes every rule.
assert.equal(mismatch('pass', judge(BASE)), null, `the exported program is the approved sequence: ${JSON.stringify(judge(BASE))}`)

// Every reference scenario passes, including the inch and multi-contour ones.
for (const name of ['part-with-holes', 'nested-sheet', 'arc-lead-ins', 'inch-output']) {
  const gcode = exportPlasma({ ...PLASMA_EXPORT_SCENARIOS[name](), machineId: 'grbl-plasma' }).result.gcode
  assert.equal(mismatch('pass', judge(gcode)), null, `${name}: the exported sequence passes`)
}

// Each mutation must trip exactly the rule it breaks.
const NEGATIVES: Array<{ name: string; program: string; fails: Rule[] }> = [
  {
    name: 'missing probe',
    program: mutate(/^G38\.2 .*$\n/m, ''),
    fails: ['probe'],
  },
  {
    name: 'missing set zero',
    program: mutate(/^G10 L20 .*$\n/m, ''),
    fails: ['zero'],
  },
  {
    name: 'missing dwell',
    program: mutate(/^G4 P.*$\n/m, ''),
    fails: ['dwell'],
  },
  {
    name: 'probe after set zero',
    program: mutate(/^G38\.2 (.*)$\n^G10 L20 (.*)$/m, 'G10 L20 $2' + '\n' + 'G38.2 $1'),
    fails: ['order'],
  },
  {
    name: 'drop without a feed',
    program: mutate(/^G1 Z([\d.]+) F[\d.]+$/m, 'G1 Z$1'),
    fails: ['feed'],
  },
  {
    name: 'positive set-zero Z',
    program: mutate(/^G10 L20 P0 Z([\d.]+)$/m, 'G10 L20 P0 Z1.000'),
    fails: ['z'],
  },
  {
    name: 'cut with the torch off',
    program: mutate(/^M5$/m, 'M5\nG1 X1 Y1 F999'),
    fails: ['torch'],
  },
  {
    name: 'rapid while the torch is on',
    program: mutate(/^M3 S1000$/m, 'M3 S1000\nG0 Z1.000'),
    fails: ['rapid'],
  },
  {
    name: 'M4 fires the torch',
    program: mutate(/^M3 S1000$/m, 'M4 S1000'),
    fails: ['mode'],
  },
]

for (const negative of NEGATIVES) {
  const findings = judge(negative.program)
  assert.equal(mismatch({ fails: negative.fails }, findings), null,
    `${negative.name}: expected exactly ${negative.fails.join(', ')}, got ${JSON.stringify(findings)}`)
}

// A mirror of the whole verdict cannot look green while it checks nothing: a
// program with no torch at all is rejected, and an expectation of failure that
// passes is an error.
{
  const noTorch = BASE.replace(/^M3 S1000$/gm, '').replace(/^G38\.2 .*$/gm, '').replace(/^G10 L20 .*$/gm, '')
  const findings = judge(noTorch)
  assert.ok(findings.some((finding) => finding.rule === 'torch'), `a program that never cuts is rejected: ${JSON.stringify(findings)}`)
  assert.match(mismatch({ fails: ['probe'] }, judge(BASE)) ?? '', /expected to be rejected \(probe\) but it passed/)
}

// The parser resolves modal motion and Z the way the controller reads them.
{
  const lines = parseProgram('G21\nG0 Z5.000\nX10 Y10\nG38.2 Z-30 F100\nG10 L20 P0 Z0\nG0 Z3.8\nM3 S1000\nG1 Z1.5 F2000\nX20 Y20 F3000\nM5\n')
  assert.equal(lines.find((line) => line.text === 'X10 Y10')?.motion, 'G0', 'a modal XY line is a rapid')
  assert.equal(lines.find((line) => line.text === 'X20 Y20 F3000')?.feed, 3000, 'a feed word carries forward')
  const probe = lines.find((line) => line.probe)!
  assert.equal(probe.motion, 'G0', 'a probe does not clear the modal motion it was preceded by')
  assert.equal(lines.find((line) => line.setZeroZ !== null)?.setZeroZ, 0)
}

console.log(`grbl-plasma verdict.test.ts: ${1 + 4} programs pass and ${NEGATIVES.length} mutations each trip exactly their own rule`)
