/**
 * Copyright 2026 Franja (Frank) Povazanj
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Sequence verdict of the G-code pierce path (issue #983), exercised without a
 * controller. Runs in `npm run check:gcode`, so the rules are tested even where
 * grbl-gvalidate is not installed.
 *
 * The positive programs are generated by the exporter itself, and every
 * negative is that same program with one load-bearing line mutated: if a
 * mutation passes, or trips fewer rules than it should, the rule it exists to
 * exercise has stopped working.
 */

import assert from 'node:assert/strict'
import { exportPlasma, PLASMA_EXPORT_SCENARIOS } from '../../../src/test/plasmaExportFixtures'
import type { PlasmaExportSpec } from '../../../src/test/plasmaExportFixtures'
import { judge, mismatch, parseProgram } from './verdict'
import type { Rule } from './verdict'

function grbl(spec: PlasmaExportSpec): string {
  return exportPlasma({ ...spec, machineId: 'grbl-plasma' }).result.gcode
}

const SINGLE = PLASMA_EXPORT_SCENARIOS['single-outline']()
const BASE = grbl(SINGLE)
assert.ok(BASE.includes('M3 S1000'), 'the fixture actually fires the torch')

/** A second, multi-contour program so the between-contours boundaries can be mutated. */
const MULTI = grbl(PLASMA_EXPORT_SCENARIOS['part-with-holes']())

/** A program with exactly one mutation applied. */
function mutateOn(program: string, pattern: RegExp, replacement: string): string {
  const mutated = program.replace(pattern, replacement)
  assert.notEqual(mutated, program, `the mutation ${pattern} matched nothing`)
  return mutated
}

/** The base program with exactly one mutation applied. */
function mutate(pattern: RegExp, replacement: string): string {
  return mutateOn(BASE, pattern, replacement)
}

// The real exported programs pass every rule. The matrix covers both units,
// line and arc leads, one and several contours, pierce height below cut height,
// a switch offset present and absent, and a mirrored physical axis.
const POSITIVES: Array<{ name: string; gcode: string }> = [
  { name: 'single-outline (mm, arc lead)', gcode: BASE },
  ...['part-with-holes', 'nested-sheet', 'small-hole', 'small-hole-arc-lead', 'arc-lead-ins', 'inch-output']
    .map((name) => ({ name, gcode: grbl(PLASMA_EXPORT_SCENARIOS[name]()) })),
  {
    name: 'pierce height below cut height',
    gcode: grbl({ ...SINGLE, operations: [{ featureIds: ['plate'], tool: { pierceHeight: 1, cutHeight: 2 } }] }),
  },
  {
    name: 'switch offset present',
    gcode: grbl({
      ...SINGLE,
      definition: (definition) => ({
        ...definition,
        plasma: { ...definition.plasma!, touchOff: { ...definition.plasma!.touchOff!, switchOffset: 5 } },
      }),
    }),
  },
  {
    name: 'switch offset absent',
    gcode: grbl({
      ...SINGLE,
      definition: (definition) => {
        const { switchOffset: _offset, ...touchOff } = definition.plasma!.touchOff!
        return { ...definition, plasma: { ...definition.plasma!, touchOff } }
      },
    }),
  },
  {
    name: 'mirrored physical X axis',
    gcode: grbl({
      ...PLASMA_EXPORT_SCENARIOS['arc-lead-ins'](),
      definition: (definition) => ({ ...definition, coordinateSystem: { ...definition.coordinateSystem, xAxis: '-X' } }),
    }),
  },
]

for (const positive of POSITIVES) {
  assert.equal(mismatch('pass', judge(positive.gcode)), null,
    `${positive.name}: the exported sequence passes: ${JSON.stringify(judge(positive.gcode))}`)
}

// Each mutation must trip exactly the rule it breaks.
const NEGATIVES: Array<{ name: string; program: string; fails: Rule[] }> = [
  {
    name: 'missing probe',
    program: mutate(/^G38\.2 .*$\n/m, ''),
    fails: ['probe'],
  },
  {
    name: 'missing set zero',
    program: mutate(/^G10 L20 .*$\n/m, ''),
    fails: ['zero'],
  },
  {
    name: 'missing dwell',
    program: mutate(/^G4 P.*$\n/m, ''),
    fails: ['dwell'],
  },
  {
    name: 'probe after set zero',
    program: mutate(/^G38\.2 (.*)$\n^G10 L20 (.*)$/m, 'G10 L20 $2' + '\n' + 'G38.2 $1'),
    fails: ['order'],
  },
  {
    name: 'drop without a feed',
    program: mutate(/^G1 Z([\d.]+) F[\d.]+$/m, 'G1 Z$1'),
    fails: ['feed'],
  },
  {
    name: 'positive set-zero Z',
    program: mutate(/^G10 L20 P0 Z([\d.]+)$/m, 'G10 L20 P0 Z1.000'),
    fails: ['z'],
  },
  {
    name: 'cut with the torch off',
    program: mutate(/^M5$/m, 'M5\nG1 X1 Y1 F999'),
    fails: ['torch'],
  },
  {
    name: 'rapid while the torch is on',
    program: mutate(/^M3 S1000$/m, 'M3 S1000\nG0 Z1.000'),
    fails: ['rapid'],
  },
  {
    name: 'M4 fires the torch',
    program: mutate(/^M3 S1000$/m, 'M4 S1000'),
    fails: ['mode'],
  },
  // The independent reviewer's three false passes, now rejected: the drop is a
  // modal carve-out, the initial safe rapid is gone, and the program is
  // truncated before M5.
  {
    name: 'missing explicit G1 Z drop',
    program: mutate(/^G1 Z[\d.]+ F[\d.]+\n/m, ''),
    fails: ['order'],
  },
  {
    name: 'missing every safe Z rapid',
    program: mutate(/^G0 Z5\.000\n/gm, ''),
    fails: ['retract', 'safeZ'],
  },
  {
    name: 'torch on at EOF (truncated before M5)',
    program: BASE.slice(0, BASE.indexOf('\nM5\n')),
    fails: ['openTorch'],
  },
  // Focused controls: each isolates one boundary.
  {
    name: 'missing only the initial safe Z',
    program: mutate(/^G0 Z5\.000\n(?=X83)/m, ''),
    fails: ['safeZ'],
  },
  {
    name: 'missing only the final retract',
    program: mutate(/^G0 Z5\.000\nM30$/m, 'M30'),
    fails: ['retract'],
  },
  {
    name: 'missing final M5',
    program: mutate(/^M5$/m, ''),
    fails: ['openTorch', 'rapid'],
  },
  {
    name: 'inherited modal Z as pierce height',
    program: mutate(/^G0 Z3\.800$/m, 'G0'),
    fails: ['order'],
  },
  {
    name: 'cut move leaves the drop cut height',
    program: mutate(/^X19\.300 Y180\.700$/m, 'X19.300 Y180.700 Z3.000'),
    fails: ['cutHeight'],
  },
  // The two remaining reviewer false passes, now rejected: the safe-Z rapid is
  // swapped after the travel to the pierce (initially and between contours), and
  // a G2/G3 or diagonal XY+Z move is used in place of the separate G1 drop.
  {
    name: 'XY travel before the initial safe Z rapid',
    program: mutate(/^G0 Z5\.000\n(X[^\n]+)\n/m, 'G0 $1\nG0 Z5.000\n'),
    fails: ['safeZ'],
  },
  {
    name: 'XY travel before the between-contour safe Z rapid',
    program: mutateOn(MULTI, /^M5\nG0 Z5\.000\n(X[^\n]+)\n/m, 'M5\nG0 $1\nG0 Z5.000\n'),
    fails: ['safeZ'],
  },
  {
    name: 'arc instead of the separate linear drop',
    program: mutate(/^G1 Z([\d.]+) F([\d.]+)$/m, 'G3 X1 Y1 Z$1 I1 J0 F$2'),
    fails: ['order'],
  },
  {
    name: 'diagonal XY+Z instead of the separate linear drop',
    program: mutate(/^G1 Z([\d.]+) F([\d.]+)$/m, 'G1 X1 Y1 Z$1 F$2'),
    fails: ['order'],
  },
]

for (const negative of NEGATIVES) {
  const findings = judge(negative.program)
  assert.equal(mismatch({ fails: negative.fails }, findings), null,
    `${negative.name}: expected exactly ${negative.fails.join(', ')}, got ${JSON.stringify(findings)}`)
}

// A mirror of the whole verdict cannot look green while it checks nothing: a
// program with no torch at all is rejected, and an expectation of failure that
// passes is an error.
{
  const noTorch = BASE.replace(/^M3 S1000$/gm, '').replace(/^G38\.2 .*$/gm, '').replace(/^G10 L20 .*$/gm, '')
  const findings = judge(noTorch)
  assert.ok(findings.some((finding) => finding.rule === 'torch'), `a program that never cuts is rejected: ${JSON.stringify(findings)}`)
  assert.match(mismatch({ fails: ['probe'] }, judge(BASE)) ?? '', /expected to be rejected \(probe\) but it passed/)
}

// The parser resolves modal motion, feed and Z the way the controller reads
// them, and keeps a line's own Z word distinct from the modal value it inherits.
{
  const lines = parseProgram('G21\nG0 Z5.000\nX10 Y10\nG38.2 Z-30 F100\nG10 L20 P0 Z0\nG0 Z3.8\nM3 S1000\nG1 Z1.5 F2000\nX20 Y20 F3000\nG3 X0 Y0 I5 J0 F3000\nM5\n')
  const modalXY = lines.find((line) => line.text === 'X10 Y10')!
  assert.equal(modalXY.motion, 'G0', 'a modal XY line is a rapid')
  assert.equal(lines.find((line) => line.text === 'X20 Y20 F3000')?.feed, 3000, 'a feed word carries forward')
  const probe = lines.find((line) => line.probe)!
  assert.equal(probe.motion, 'G0', 'a probe does not clear the modal motion it was preceded by')
  assert.equal(lines.find((line) => line.setZeroZ !== null)?.setZeroZ, 0)
  assert.equal(modalXY.explicitZ, null, 'a modal XY line carries no Z word of its own')
  assert.equal(modalXY.z, 5, 'but it inherits the modal Z')
  assert.equal(lines.find((line) => line.text === 'G0 Z3.8')?.explicitZ, 3.8, 'an explicit rapid keeps its own Z word')
  assert.equal(lines.find((line) => line.text === 'X20 Y20 F3000')?.explicitZ, null, 'a cut XY line inherits its Z')
  // Lateral and arc words are tracked from the line itself: the drop is Z-only,
  // the travel carries X/Y, and an arc word does not set a Z of its own.
  assert.equal(modalXY.explicitX && modalXY.explicitY, true, 'a travel line carries its own X and Y words')
  const drop = lines.find((line) => line.text === 'G1 Z1.5 F2000')!
  assert.equal(drop.explicitX || drop.explicitY || drop.arcWord, false, 'the separate drop carries no X, Y or arc word')
  const arc = lines.find((line) => line.text === 'G3 X0 Y0 I5 J0 F3000')!
  assert.equal(arc.arcWord, true, 'an arc word is tracked')
  assert.equal(arc.explicitZ, null, 'an arc word alone does not set a Z')
}

console.log(`grbl-plasma verdict.test.ts: ${POSITIVES.length} programs pass and ${NEGATIVES.length} mutations each trip exactly their own rule`)
