/**
 * Copyright 2026 Franja (Frank) Povazanj
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * A project as it sits on the machine for one setup (issue #946).
 *
 * Toolpath generators know one frame: the cutter comes down along +Z onto the
 * face that is up. A Bottom operation is generated by handing them the whole
 * project turned into that frame — stock, every feature, tabs and clamps — and
 * carrying the result back into stock space afterwards. No generator learns
 * that a setup exists, and a Bottom pocket is by construction the same
 * toolpath as that pocket drawn mirrored on a Top-only project.
 *
 * What is turned, and how:
 *
 * - **features** — the plan-view mirror is composed onto each instance
 *   transform, and the Z span is reflected through mid-thickness, so the span
 *   stays a span (`z_top` above `z_bottom`). Every feature is turned, whichever
 *   face it was drawn on: a feature is a volume in the stock, and the volume is
 *   what the cutter meets.
 * - **stock** — its outline is mirrored. The pivot is the centre of its
 *   bounds, so the turned stock occupies the same box.
 * - **tabs and clamps** — both are positions on the stock, so they mirror with
 *   it. A tab's Z span is reflected like a feature's; a clamp keeps its height,
 *   which is measured above whichever face is up.
 * - **the origin is not turned** — it is one placement shared by every setup,
 *   already read in the setup-local frame (see `setupOrientation.ts`).
 *
 * - **imported 3D models** — a model has a back face, and a Bottom setup
 *   machines it. Its silhouette and Z span turn like any feature's; the mesh
 *   is what is left, and it is turned at the one place every generator loads
 *   it. The model's data is marked turned over (`modelDataTurnedOver`), and
 *   `loadSTLTransformedGeometry` reflects the mesh inside its already
 *   reflected span — with the plan mirror, exactly the half turn.
 */

import type { Clamp, FeatureDefinition, FeatureInstance, Matrix2D, Point, Project, Tab } from '../types/project'
import { modelDataTurnedOver } from './importedModelTransform'
import { multiplyMatrix } from '../store/helpers/instanceTransforms'
import { mirrorProfile } from '../store/helpers/transform'
import { resolveDimensionRef } from './toolpaths/geometry'
import type { DrillCycle, ToolpathBounds, ToolpathMove, ToolpathPoint, ToolpathResult } from './toolpaths/types'
import { setupToCanonicalPoint } from './setupOrientation'
import type { SetupFrame } from './setupOrientation'

/**
 * The plan-view half of a setup's turn, as an instance-transform matrix: a
 * mirror across the flip axis through the stock centre. Written with the same
 * `2·pivot − value` arithmetic as the point transform, so a profile resolved
 * through this matrix lands on exactly the points `canonicalToSetupPoint`
 * gives.
 */
export function setupPlanMirror(frame: SetupFrame): Matrix2D {
  return frame.orientation.axis === 'x'
    ? { a: 1, b: 0, c: 0, d: -1, e: 0, f: 2 * frame.pivot.y }
    : { a: -1, b: 0, c: 0, d: 1, e: 2 * frame.pivot.x, f: 0 }
}

function turnZ(z: number, frame: SetupFrame): number {
  return 2 * frame.pivot.z - z
}

function turnFeature(project: Project, feature: FeatureInstance, mirror: Matrix2D, frame: SetupFrame): FeatureInstance {
  return {
    ...feature,
    transform: multiplyMatrix(mirror, feature.transform),
    // Resolved to numbers: a named dimension holds the stock-space value, and
    // the turned span has no name. Top and bottom trade places so the span
    // still reads top-above-bottom.
    z_top: turnZ(resolveDimensionRef(project, feature.z_bottom), frame),
    z_bottom: turnZ(resolveDimensionRef(project, feature.z_top), frame),
  }
}

/** An axis-aligned rectangle mirrors to an axis-aligned rectangle. */
function turnRect<T extends { x: number; y: number; w: number; h: number }>(rect: T, frame: SetupFrame): T {
  return frame.orientation.axis === 'x'
    ? { ...rect, y: 2 * frame.pivot.y - (rect.y + rect.h) }
    : { ...rect, x: 2 * frame.pivot.x - (rect.x + rect.w) }
}

function turnTab(tab: Tab, frame: SetupFrame): Tab {
  return { ...turnRect(tab, frame), z_top: turnZ(tab.z_bottom, frame), z_bottom: turnZ(tab.z_top, frame) }
}

function turnClamp(clamp: Clamp, frame: SetupFrame): Clamp {
  return turnRect(clamp, frame)
}

/**
 * Definitions with every imported model marked turned over. The record is
 * returned untouched for a project without models, which is most of them.
 */
function turnModelDefinitions(definitions: Project['featureDefinitions']): Project['featureDefinitions'] {
  let turned: Record<string, FeatureDefinition> | null = null
  for (const [id, definition] of Object.entries(definitions)) {
    if (definition.kind !== 'stl' || !definition.stl) continue
    turned ??= { ...definitions }
    turned[id] = { ...definition, stl: modelDataTurnedOver(definition.stl) }
  }
  return turned ?? definitions
}

/**
 * The project turned into a setup's frame. `frame` is undefined for a Top
 * setup, and the project is then returned as it is — the same object — so a
 * Top operation cannot generate differently from how it did before setups
 * existed.
 *
 * The result is an ordinary top-down project: its setups all read as
 * unturned, so nothing handed this project turns it a second time. It is a
 * transient read model for generation and must never be stored.
 */
export function projectInSetupFrame(project: Project, frame: SetupFrame | undefined): Project {
  if (!frame || frame.orientation.angleDeg === 0) return project

  const mirror = setupPlanMirror(frame)
  const mirrorPoint = (point: Point): Point => (
    frame.orientation.axis === 'x'
      ? { x: point.x, y: 2 * frame.pivot.y - point.y }
      : { x: 2 * frame.pivot.x - point.x, y: point.y }
  )

  return {
    ...project,
    stock: {
      ...project.stock,
      profile: mirrorProfile(project.stock.profile, mirrorPoint),
      sourceFeature: project.stock.sourceFeature
        ? turnFeature(project, project.stock.sourceFeature, mirror, frame)
        : project.stock.sourceFeature,
    },
    featureDefinitions: turnModelDefinitions(project.featureDefinitions),
    features: project.features.map((feature) => turnFeature(project, feature, mirror, frame)),
    tabs: project.tabs.map((tab) => turnTab(tab, frame)),
    clamps: project.clamps.map((clamp) => turnClamp(clamp, frame)),
    setups: project.setups?.map((setup) => ({
      ...setup,
      orientation: { axis: setup.orientation.axis, angleDeg: 0 },
    })),
  }
}

function boundsOf(points: readonly ToolpathPoint[]): ToolpathBounds {
  const bounds: ToolpathBounds = {
    minX: Infinity, minY: Infinity, minZ: Infinity,
    maxX: -Infinity, maxY: -Infinity, maxZ: -Infinity,
  }
  for (const point of points) {
    bounds.minX = Math.min(bounds.minX, point.x)
    bounds.minY = Math.min(bounds.minY, point.y)
    bounds.minZ = Math.min(bounds.minZ, point.z)
    bounds.maxX = Math.max(bounds.maxX, point.x)
    bounds.maxY = Math.max(bounds.maxY, point.y)
    bounds.maxZ = Math.max(bounds.maxZ, point.z)
  }
  return bounds
}

/**
 * A toolpath generated in a setup's frame, carried back into stock space —
 * the frame every toolpath is stored in, and the one the export pipeline
 * turns from. A Bottom operation's path therefore approaches from under the
 * stock, with its clearance at negative stock Z.
 *
 * Moves keep their order and count, so indices into `moves`
 * (`collidingMoveIndices`) still name the same moves. Returns the same object
 * for a Top setup.
 */
export function toolpathInStockFrame<T extends ToolpathResult>(result: T, frame: SetupFrame | undefined): T {
  if (!frame || frame.orientation.angleDeg === 0) return result

  const turn = (point: ToolpathPoint): ToolpathPoint => setupToCanonicalPoint(point, frame)
  const moves: ToolpathMove[] = result.moves.map((move) => ({ ...move, from: turn(move.from), to: turn(move.to) }))

  const turned: T = { ...result, moves }
  if (result.bounds) {
    const { minX, minY, minZ, maxX, maxY, maxZ } = result.bounds
    turned.bounds = boundsOf([turn({ x: minX, y: minY, z: minZ }), turn({ x: maxX, y: maxY, z: maxZ })])
  }
  if (result.drillCycles) {
    turned.drillCycles = result.drillCycles.map((cycle): DrillCycle => {
      const at = turn({ x: cycle.x, y: cycle.y, z: cycle.bottomZ })
      return {
        ...cycle,
        x: at.x,
        y: at.y,
        bottomZ: at.z,
        clearZ: turnZ(cycle.clearZ, frame),
        retractZ: turnZ(cycle.retractZ, frame),
      }
    })
  }
  // Cut levels are Z heights like any other (`PocketToolpathResult`).
  const levels = (result as { stepLevels?: unknown }).stepLevels
  if (Array.isArray(levels)) {
    (turned as { stepLevels?: number[] }).stepLevels = (levels as number[]).map((z) => turnZ(z, frame))
  }
  return turned
}

/**
 * A stock-space toolpath as the machine runs it in its setup: Z measured up
 * from the bed with the cutter coming down, whichever face is up. This is the
 * frame an operator reads heights in, so reports use it. A half turn undoes
 * itself, so this is the same mapping as {@link toolpathInStockFrame}; the two
 * names say which way a caller is going.
 */
export function toolpathInSetupFrame<T extends ToolpathResult>(result: T, frame: SetupFrame | undefined): T {
  return toolpathInStockFrame(result, frame)
}
