/**
 * Copyright 2026 Franja (Frank) Povazanj
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * One setup's simulation input, end to end (issue #947).
 *
 * The fixtures are real: pockets are generated by the shipped #946 generation
 * path, replayed on fresh stock by the unchanged heightfield engine, and — for
 * a Bottom setup — compared against the program the shipped per-setup exporter
 * emits and a parser reads back. Nothing is stubbed, so a frame this module
 * gets wrong can only show up as motion in the wrong place.
 *
 * Mutations these assertions were checked against, both applied to
 * `simulationSetup.ts` on their own and reverted:
 * - the toolpath turn dropped (`toolpathInSetupFrame` → the input path)
 *   → "Bottom paths are the stock-space paths turned once" and the export
 *   parity fixture fail;
 * - setup membership widened (`(operationSetup ?? topSetup)?.id === setup.id`
 *   → always true) → "Bottom input holds only Bottom operations" fails.
 *
 * Run with: npx tsx src/app/simulationSetup.test.ts
 */

import {
  circleProfile, defaultTool, newProject, polygonProfile, rectProfile,
  type Clamp, type Operation, type Point, type Project, type SetupFace,
  type SetupOrientation, type SketchFeature, type Tab,
} from '../types/project'
import { BOTTOM_SETUP_ID, projectWithFeatures, withBottomSetup, withoutSetupFields } from '../test/projectFixtures'
import { syncProjectSetups } from '../store/helpers/setups'
import { activeSetup } from '../store/helpers/activeFace'
import { provisionalSetupId } from '../store/helpers/provisionalSetup'
import { canonicalToSetupPoint, setupFace, setupFrame } from '../engine/setupOrientation'
import { projectInSetupFrame } from '../engine/setupFrameProject'
import { computeOperationToolpath } from '../engine/toolpaths/generateOperation'
import { normalizeToolForProject } from '../engine/toolpaths/geometry'
import type { PocketToolpathResult, ToolpathResult } from '../engine/toolpaths/types'
import { simulateReplayItemsHeightfield, type SimulationGrid, type SimulationResult } from '../engine/simulation'
import { findMillingOperationTool } from '../toolPolicy'
import { BUNDLED_DEFINITIONS } from '../engine/gcode/definitions'
import { runPostProcessor } from '../engine/gcode/postprocessor'
import { parseExportedMotion } from '../engine/gcode/motionDebug'
import { validateMachineDefinition, type MachineDefinition } from '../engine/gcode/types'
import { projectToMachinePoint } from '../engine/gcode/utils'
import { buildSimulationSetupInput, type SimulationSetupInput } from './simulationSetup'

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`Assertion failed: ${message}`)
}

function assertEqual<T>(actual: T, expected: T, label: string): void {
  assert(
    JSON.stringify(actual) === JSON.stringify(expected),
    `${label}: got ${JSON.stringify(actual)}, expected ${JSON.stringify(expected)}`,
  )
}

type Axis = SetupOrientation['axis']

// ── Fixtures ──────────────────────────────────────────────────

interface FixtureSpec {
  units: 'mm' | 'inch'
  stockX: number
  stockY: number
  width: number
  height: number
  thickness: number
  toolDiameter: number
  depth: number
  topRect: { x: number; y: number; w: number; h: number }
  bottomRect: { x: number; y: number; w: number; h: number }
}

const MM: FixtureSpec = {
  // Off the origin, so a pivot taken about (0, 0) rather than the stock centre shows.
  units: 'mm', stockX: 10, stockY: 5, width: 100, height: 80, thickness: 20,
  toolDiameter: 6, depth: 6,
  // Asymmetric and nowhere near the stock centre, so a wrong pivot or axis shows.
  topRect: { x: 20, y: 15, w: 24, h: 14 },
  bottomRect: { x: 72, y: 32, w: 20, h: 16 },
}

const INCH: FixtureSpec = {
  units: 'inch', stockX: 0, stockY: 0, width: 4, height: 3, thickness: 0.5,
  toolDiameter: 0.25, depth: 0.15,
  topRect: { x: 0.4, y: 0.3, w: 1.0, h: 0.6 },
  bottomRect: { x: 2.5, y: 1.0, w: 0.8, h: 0.6 },
}

function operation(overrides: Partial<Operation> & Pick<Operation, 'kind' | 'target'>): Operation {
  return {
    id: 'op1', name: 'op', pass: 'rough', enabled: true, showToolpath: true, debugToolpath: false,
    toolRef: 't1', stepdown: 2, stepover: 0.4, feed: 800, plungeFeed: 300, rpm: 18000,
    pocketPattern: 'offset', pocketAngle: 0, stockToLeaveRadial: 0, stockToLeaveAxial: 0,
    finishWalls: true, finishFloor: true, carveDepth: 2, maxCarveDepth: 2,
    cutDirection: 'conventional', machiningOrder: 'level_first', ...overrides,
  }
}

function pocketFeature(
  id: string,
  rect: { x: number; y: number; w: number; h: number },
  zTop: number,
  zBottom: number,
  authoringFace: SetupFace,
): SketchFeature {
  return {
    id, name: id, kind: 'rect', folderId: null,
    sketch: {
      profile: rectProfile(rect.x, rect.y, rect.w, rect.h),
      origin: { x: 0, y: 0 }, orientationAngle: 0, dimensions: [], constraints: [],
    },
    operation: 'subtract', z_top: zTop, z_bottom: zBottom,
    authoringFace, visible: true, locked: false,
  }
}

/** A project with one Top pocket and one Bottom pocket, each in its own setup. */
function makeProject(spec: FixtureSpec, axis: Axis = 'x'): Project {
  const base = newProject(`sim-setup-${spec.units}`, spec.units)
  base.meta = { ...base.meta, operationClearanceZ: spec.thickness * 0.4 }
  base.stock = {
    ...base.stock, profile: rectProfile(spec.stockX, spec.stockY, spec.width, spec.height),
    thickness: spec.thickness,
  }
  base.origin = { name: 'Origin', x: spec.stockX, y: spec.stockY + spec.height, z: spec.thickness, visible: true }
  base.tools = [{
    ...defaultTool(spec.units, 1), id: 't1', name: 'Flat endmill',
    diameter: spec.toolDiameter, maxCutDepth: spec.thickness * 2,
  }]
  const features = [
    // A pocket opening at the top face, cut down `depth`.
    pocketFeature('top-pocket', spec.topRect, spec.thickness, spec.thickness - spec.depth, 'top'),
    // A pocket opening at the bottom face, cut up `depth`.
    pocketFeature('bottom-pocket', spec.bottomRect, spec.depth, 0, 'bottom'),
  ]
  const withFeatures = projectWithFeatures(base, features)
  const feed = spec.units === 'inch' ? 30 : 600
  const plungeFeed = spec.units === 'inch' ? 12 : 180
  const shared = {
    kind: 'pocket' as const, toolRef: 't1', setupId: withFeatures.activeSetupId,
    stepdown: spec.depth, stepover: 0.4, feed, plungeFeed,
  }
  const operations: Operation[] = [
    operation({ ...shared, id: 'opTop', name: 'Top pocket', target: { source: 'features', featureIds: ['top-pocket'] } }),
    operation({ ...shared, id: 'opBottom', name: 'Bottom pocket', target: { source: 'features', featureIds: ['bottom-pocket'] } }),
  ]
  const synced = syncProjectSetups({ ...withFeatures, operations })
  return withBottomSetup(synced, { axis, operationIds: ['opBottom'] })
}

function topSetupOf(project: Project) {
  const setup = project.setups.find((entry) => setupFace(entry) === 'top')
  assert(setup, 'fixture: the project has a Top setup')
  return setup
}

function bottomSetupOf(project: Project) {
  const setup = project.setups.find((entry) => entry.id === BOTTOM_SETUP_ID)
  assert(setup, 'fixture: the project has a Bottom setup')
  return setup
}

/** Every operation's generated stock-space result, by id. */
function generatePaths(project: Project): Map<string, ToolpathResult> {
  const paths = new Map<string, ToolpathResult>()
  for (const op of project.operations) {
    const envelope = computeOperationToolpath(project, op)
    assert(envelope, `fixture: ${op.id} is generated`)
    paths.set(op.id, envelope.result)
  }
  return paths
}

/** The consumer's replay: every operation of the setup, into one fresh grid. */
function replaySetup(input: SimulationSetupInput, targetLongAxisCells = 140): SimulationResult {
  const items = input.operations.flatMap((op) => {
    const toolpath = input.toolpaths.get(op.id)
    const tool = findMillingOperationTool(input.project, op)
    if (!toolpath || !tool) return []
    const normalized = normalizeToolForProject(tool, input.project)
    return [{
      operationId: op.id,
      operationName: op.name,
      toolRef: tool.id,
      toolType: tool.type,
      toolRadius: normalized.radius,
      vBitAngle: normalized.vBitAngle,
      toolpath,
    }]
  })
  return simulateReplayItemsHeightfield(input.project, items, { targetLongAxisCells })
}

function topZAt(grid: SimulationGrid, x: number, y: number): number {
  const col = Math.min(grid.cols - 1, Math.max(0, Math.floor((x - grid.originX) / grid.cellSize)))
  const row = Math.min(grid.rows - 1, Math.max(0, Math.floor((y - grid.originY) / grid.cellSize)))
  return grid.topZ[row * grid.cols + col]
}

/** An independent plan mirror — literal arithmetic, not the engine's. */
function mirrorXY(point: Point, axis: Axis, spec: FixtureSpec): Point {
  const cx = spec.stockX + spec.width / 2
  const cy = spec.stockY + spec.height / 2
  return axis === 'x' ? { x: point.x, y: 2 * cy - point.y } : { x: 2 * cx - point.x, y: point.y }
}

function centerOf(rect: { x: number; y: number; w: number; h: number }): Point {
  return { x: rect.x + rect.w / 2, y: rect.y + rect.h / 2 }
}

// ── Scoping, frame and identity ───────────────────────────────

function testTopIsTheSameObjects(): void {
  console.log('Testing a Top input hands back the caller\'s own objects...')
  const project = makeProject(MM)
  const paths = generatePaths(project)
  const input = buildSimulationSetupInput(project, topSetupOf(project), paths)

  assert(input.project === project, 'the project is the same object')
  assert(input.toolpaths.get('opTop') === paths.get('opTop'), 'a Top path is the same object')
  assertEqual(input.operations.map((op) => op.id), ['opTop'], 'a Top input holds only Top operations')
  assertEqual([...input.toolpaths.keys()], ['opTop'], 'and only their paths')
}

function testDisabledAndHiddenOperationsAreIncluded(): void {
  console.log('Testing disabled and hidden operations stay in scope, missing paths stay missing...')
  const project = makeProject(MM)
  const paths = generatePaths(project)
  const top = topSetupOf(project)
  const hidden: Operation = operation({
    id: 'opHidden',
    name: 'Hidden',
    kind: 'pocket',
    target: { source: 'features', featureIds: ['top-pocket'] },
    setupId: top.id,
    enabled: false,
    showToolpath: false,
  })
  const withHidden: Project = { ...project, operations: [...project.operations, hidden] }

  const input = buildSimulationSetupInput(withHidden, top, paths)
  assertEqual(input.operations.map((op) => op.id), ['opTop', 'opHidden'], 'a disabled, hidden operation is still listed')
  assertEqual([...input.toolpaths.keys()], ['opTop'], 'its missing path is not invented')

  // Dropping the acquired path for an in-scope operation keeps it missing.
  const withoutBottom = new Map(paths)
  withoutBottom.delete('opBottom')
  const bottomInput = buildSimulationSetupInput(project, bottomSetupOf(project), withoutBottom)
  assertEqual(bottomInput.operations.map((op) => op.id), ['opBottom'], 'the operation is still listed without its path')
  assert(bottomInput.toolpaths.size === 0, 'and its path is still missing')
}

function testLegacyOperationsReadAsTop(): void {
  console.log('Testing a pre-setup project resolves its operations to Top...')
  const project = makeProject(MM)
  const paths = generatePaths(project)
  const legacy = withoutSetupFields(project) as unknown as Project
  assert(legacy.setups === undefined, 'fixture: the legacy project has no setups')

  const input = buildSimulationSetupInput(legacy, activeSetup(legacy), paths)
  assert(input.project === legacy, 'the legacy project comes back untouched')
  assertEqual(input.operations.map((op) => op.id), ['opTop', 'opBottom'], 'every operation with no setupId reads as Top')
  assertEqual([...input.toolpaths.keys()], ['opTop', 'opBottom'], 'and its paths are the same objects')
  assert(input.toolpaths.get('opTop') === paths.get('opTop'), 'no copy for a Top path')
}

function testBottomIsScopedAndTurned(): void {
  console.log('Testing a Bottom input is scoped to its setup and turned once...')
  const project = makeProject(MM)
  const paths = generatePaths(project)
  const bottom = bottomSetupOf(project)
  const canonicalSnapshot = JSON.stringify({
    stock: project.stock,
    operations: project.operations,
    path: paths.get('opBottom'),
  })

  const input = buildSimulationSetupInput(project, bottom, paths)
  assert(input.project !== project, 'a Bottom project is a turned copy')
  assert(input.project.stock.profile !== project.stock.profile, 'its stock outline is a copy too')
  assertEqual(input.operations.map((op) => op.id), ['opBottom'], 'only the Bottom setup\'s operations')
  assertEqual([...input.toolpaths.keys()], ['opBottom'], 'and only their paths')

  const local = input.toolpaths.get('opBottom')
  const canonical = paths.get('opBottom')
  assert(local && canonical, 'fixture: both paths exist')
  assert(local !== canonical, 'the Bottom path is a turned copy')

  const frame = setupFrame(bottom.orientation, project.stock)
  canonical.moves.forEach((move, index) => {
    const got = local.moves[index]
    const expected = canonicalToSetupPoint(move.to, frame)
    assert(
      Math.abs(got.to.x - expected.x) < 1e-9 && Math.abs(got.to.y - expected.y) < 1e-9 && Math.abs(got.to.z - expected.z) < 1e-9,
      `move ${index}: local (${got.to.x}, ${got.to.y}, ${got.to.z}) is not the stock point turned once`,
    )
  })

  assertEqual(
    JSON.stringify({ stock: project.stock, operations: project.operations, path: paths.get('opBottom') }),
    canonicalSnapshot,
    'the original project, operations and path are not written to',
  )
}

function testProvisionalAndEmptyBottom(): void {
  console.log('Testing a provisional Bottom setup is valid and empty until materialized...')
  const topOnly = makeProject(MM)
  const topOnlyProject: Project = {
    ...topOnly,
    setups: topOnly.setups.filter((entry) => entry.id !== BOTTOM_SETUP_ID),
    operations: topOnly.operations.map((op) => ({ ...op, setupId: topOnly.activeSetupId })),
    activeSetupId: provisionalSetupId('bottom'),
  }
  const paths = generatePaths(topOnlyProject)
  const provisional = activeSetup(topOnlyProject)
  assert(provisional.id === provisionalSetupId('bottom'), 'fixture: the workspace is on a provisional Bottom setup')
  assert(!topOnlyProject.setups.some((entry) => entry.id === provisional.id), 'fixture: it is not one of the project\'s setups')

  const provisionalInput = buildSimulationSetupInput(topOnlyProject, provisional, paths)
  assertEqual(provisionalInput.operations, [], 'a provisional Bottom setup has no operations')
  assert(provisionalInput.toolpaths.size === 0, 'and acquires no paths')
  assert(provisionalInput.project !== topOnlyProject, 'it is still simulated in its turned frame')

  // A real Bottom setup that simply has no operations yet behaves the same.
  const emptyReal = withBottomSetup(topOnlyProject, { axis: 'x' })
  const emptyInput = buildSimulationSetupInput(emptyReal, bottomSetupOf(emptyReal), paths)
  assertEqual(emptyInput.operations, [], 'a materialized but empty Bottom setup has no operations')
  assert(emptyInput.toolpaths.size === 0, 'and no paths')
}

function testInvalidExplicitSetupThrows(): void {
  console.log('Testing an operation naming a missing setup is refused...')
  const project = makeProject(MM)
  const paths = generatePaths(project)
  const dangling: Project = {
    ...project,
    operations: project.operations.map((op) => (op.id === 'opBottom' ? { ...op, setupId: 'gone' } : op)),
  }
  let threw = false
  try {
    buildSimulationSetupInput(dangling, bottomSetupOf(dangling), paths)
  } catch {
    threw = true
  }
  assert(threw, 'a dangling setup id stops the input build rather than reading as Top')
}

// ── Fresh-stock simulation ────────────────────────────────────

function testFreshStockSimulation(spec: FixtureSpec): void {
  console.log(`Testing fresh-stock Top and Bottom simulation (${spec.units})...`)
  const project = makeProject(spec, 'x')
  const paths = generatePaths(project)
  const topCenter = centerOf(spec.topRect)
  const bottomCenter = centerOf(spec.bottomRect)

  // Top: the pocket opening at the top face is removed from the top down.
  const topResult = replaySetup(buildSimulationSetupInput(project, topSetupOf(project), paths))
  assert(topResult.stats.removedCellCount > 0, 'the Top setup removes material')
  assert(topZAt(topResult.grid, topCenter.x, topCenter.y) < spec.thickness - spec.depth * 0.5, 'the Top pocket is cut at its centre')
  assert(Math.abs(topZAt(topResult.grid, bottomCenter.x, bottomCenter.y) - spec.thickness) < 1e-6, 'the Top pocket does not reach the Bottom pocket')

  for (const axis of ['x', 'y'] as const) {
    // Regenerated for this flip: which way the stock turns changes the
    // generated stock-space path, so reusing the other axis would compare the
    // wrong motion.
    const axisProject = makeProject(spec, axis)
    const axisPaths = generatePaths(axisProject)
    const bottom = bottomSetupOf(axisProject)
    const input = buildSimulationSetupInput(axisProject, bottom, axisPaths)
    const result = replaySetup(input)

    const localBottom = mirrorXY(bottomCenter, axis, spec)
    const localTop = mirrorXY(topCenter, axis, spec)

    assert(result.stats.removedCellCount > 0, `about ${axis}: the Bottom setup removes material`)
    assert(
      topZAt(result.grid, localBottom.x, localBottom.y) < spec.thickness - spec.depth * 0.5,
      `about ${axis}: the Bottom pocket is cut at its flipped position`,
    )
    assert(
      Math.abs(topZAt(result.grid, localTop.x, localTop.y) - spec.thickness) < 1e-6,
      `about ${axis}: the Top pocket's flipped position is untouched on fresh stock`,
    )
    // The cut reaches the pocket floor measured from the top of the flipped stock.
    assert(
      Math.abs(result.stats.minTopZ - (spec.thickness - spec.depth)) <= 2 * result.grid.cellSize,
      `about ${axis}: the Bottom floor is ${spec.thickness - spec.depth} from the flipped top, got ${result.stats.minTopZ}`,
    )

    // In the local frame the Bottom cutter comes down from above the stock.
    const localPath = input.toolpaths.get('opBottom')
    assert(localPath, `about ${axis}: the Bottom path is in the input`)
    const cuts = localPath.moves.filter((move) => move.kind === 'cut' || move.kind === 'plunge')
    assert(cuts.length > 0, `about ${axis}: the Bottom path cuts`)
    for (const move of cuts) {
      assert(
        move.to.z > spec.thickness - spec.depth - 1e-9 && move.to.z <= spec.thickness + 1e-9,
        `about ${axis}: a local cut at Z ${move.to.z} is outside the top ${spec.depth} of the flipped stock`,
      )
    }
  }
}

// ── Export parity ─────────────────────────────────────────────

function bundled(id: string, overrides?: Partial<MachineDefinition>): MachineDefinition {
  const found = BUNDLED_DEFINITIONS.find((definition) => definition.id === id)
  if (!found) throw new Error(`Fixture error: no bundled definition "${id}"`)
  return validateMachineDefinition({ ...structuredClone(found), ...overrides })
}

function testExportParity(spec: FixtureSpec): void {
  console.log(`Testing Bottom simulation motion equals the parsed exported program (${spec.units})...`)
  const project = makeProject(spec, 'x')
  const paths = generatePaths(project)
  const bottom = bottomSetupOf(project)
  const input = buildSimulationSetupInput(project, bottom, paths)
  const operation = input.operations[0]
  const localPath = input.toolpaths.get(operation.id)
  assert(localPath, 'fixture: the Bottom path is in the input')

  // Straight-line moves only: arc fitting legitimately drops the intermediate
  // endpoints of a fitted run, which this comparison would misread as a
  // mismatch rather than a different (valid) way to write the same path.
  const grbl = bundled('grbl')
  const definition = bundled('grbl', { motion: { ...grbl.motion, arcInterpolation: false } })

  const tool = findMillingOperationTool(project, operation)
  assert(tool, 'fixture: the operation has a tool')
  const program = runPostProcessor({
    project,
    definition,
    operations: [{ operation, tool: normalizeToolForProject(tool, project), toolpath: paths.get(operation.id)! }],
    options: { emitToolChanges: true, emitCoolant: false, programName: project.meta.name },
  }).gcode

  const unitsCommand = spec.units === 'inch' ? definition.units.inchCommand : definition.units.mmCommand
  assert(unitsCommand !== null, 'fixture: the definition declares a units command')
  assert(program.includes(unitsCommand), `the program declares ${unitsCommand}`)

  const parsed = parseExportedMotion(program, definition)
  assert(parsed.status === 'verified', `the program parses cleanly, got "${parsed.status}"`)

  const expected = localPath.moves
    .filter((move) => move.kind !== 'rapid')
    .map((move) => projectToMachinePoint(move.to, project.origin, definition))
  const actual = parsed.moves.filter((move) => move.kind !== 'rapid').map((move) => move.to)
  assert(expected.length > 0, 'fixture: the Bottom path has emitted non-rapid motion')
  assert(
    actual.length === expected.length,
    `every local move is emitted: ${actual.length} parsed non-rapid endpoints, expected ${expected.length}`,
  )

  const decimalPlaces = definition.numberFormat.decimalPlaces[spec.units]
  const tolerance = 0.5 * 10 ** -decimalPlaces + 1e-9
  expected.forEach((point, index) => {
    const got = actual[index]
    const matches = Math.abs(got.x - point.x) <= tolerance
      && Math.abs(got.y - point.y) <= tolerance
      && Math.abs(got.z - point.z) <= tolerance
    assert(
      matches,
      `endpoint ${index} is (${got.x}, ${got.y}, ${got.z}), expected (${point.x}, ${point.y}, ${point.z}) within ${tolerance}`,
    )
  })

  // Sanity: the no-arc clone differs from the arc-capable default only in a way
  // this fixture would not accept silently.
  assert(grbl.motion.arcInterpolation === true, 'fixture: the bundled GRBL can interpolate arcs')
}

// ── Drill metadata and cut levels ─────────────────────────────

function testDrillAndLevelMetadataPreserved(): void {
  console.log('Testing drill cycles and pocket levels survive the turn...')
  const project = makeProject(MM)
  const paths = generatePaths(project)
  const bottom = bottomSetupOf(project)
  const input = buildSimulationSetupInput(project, bottom, paths)

  const canonicalPocket = paths.get('opBottom') as PocketToolpathResult
  const localPocket = input.toolpaths.get('opBottom') as PocketToolpathResult
  assert(Array.isArray(canonicalPocket.stepLevels) && canonicalPocket.stepLevels.length > 0, 'fixture: the pocket has cut levels')
  assertEqual(
    localPocket.stepLevels,
    canonicalPocket.stepLevels.map((z) => MM.thickness - z),
    'cut levels are reflected through the stock',
  )

  // A real Bottom drilling operation: the hole, its depths and its peck survive.
  const base = newProject('sim-setup-drill', 'mm')
  base.stock = { ...base.stock, profile: rectProfile(0, 0, 100, 80), thickness: 20 }
  base.origin = { name: 'Origin', x: 0, y: 80, z: 20, visible: true }
  base.tools = [{ ...defaultTool('mm', 1), id: 't1', name: 'Drill 3', type: 'drill', diameter: 3 }]
  const hole: SketchFeature = {
    id: 'hole',
    name: 'hole',
    kind: 'circle',
    folderId: null,
    sketch: {
      profile: circleProfile(20, 15, 3),
      origin: { x: 0, y: 0 },
      orientationAngle: 0,
      dimensions: [],
      constraints: [],
    },
    operation: 'subtract',
    z_top: 8,
    z_bottom: 0,
    authoringFace: 'bottom',
    visible: true,
    locked: false,
  }
  const drill = operation({
    id: 'opDrill',
    name: 'Drill',
    kind: 'drilling',
    drillType: 'peck',
    peckDepth: 2,
    target: { source: 'features', featureIds: ['hole'] },
    setupId: base.activeSetupId,
    stepdown: 2,
  })
  const drillProject = withBottomSetup(
    syncProjectSetups({ ...projectWithFeatures(base, [hole]), operations: [drill] }),
    { axis: 'x', operationIds: ['opDrill'] },
  )
  const drillPaths = generatePaths(drillProject)
  const drillBottom = bottomSetupOf(drillProject)
  const drillInput = buildSimulationSetupInput(drillProject, drillBottom, drillPaths)
  const canonical = drillPaths.get('opDrill')
  const local = drillInput.toolpaths.get('opDrill')
  assert(canonical?.drillCycles && local?.drillCycles, 'fixture: both carry drill cycles')
  assert(canonical.drillCycles.length === local.drillCycles.length, 'one cycle per hole')
  const drillFrame = setupFrame(drillBottom.orientation, drillProject.stock)
  canonical.drillCycles.forEach((cycle, index) => {
    const got = local.drillCycles![index]
    const at = canonicalToSetupPoint({ x: cycle.x, y: cycle.y, z: 0 }, drillFrame)
    assert(Math.abs(got.x - at.x) < 1e-9 && Math.abs(got.y - at.y) < 1e-9, `cycle ${index} is at the flipped position`)
    assert(Math.abs(got.bottomZ - (20 - cycle.bottomZ)) < 1e-9, `cycle ${index} bottom Z is reflected`)
    assert(Math.abs(got.clearZ - (20 - cycle.clearZ)) < 1e-9, `cycle ${index} clearance is reflected`)
    assert(Math.abs(got.retractZ - (20 - cycle.retractZ)) < 1e-9, `cycle ${index} retract is reflected`)
    assert(got.drillType === cycle.drillType && got.peckDepth === cycle.peckDepth, `cycle ${index} keeps its metadata`)
  })
  assert(local !== canonical, 'the drilling path is a turned copy')
}

// ── Stock profile, tabs and clamps ────────────────────────────

function testStockProfileTabsAndClampsAreTurned(): void {
  console.log('Testing the turned frame carries stock profile, tabs and clamps...')
  const project = makeProject(MM)
  const tab: Tab = { id: 'tab', name: 'Tab', x: 30, y: 10, w: 8, h: 6, z_top: 3, z_bottom: 0, visible: true }
  const clamp: Clamp = { id: 'clamp', name: 'Clamp', type: 'step_clamp', x: 90, y: 60, w: 15, h: 20, height: 12, visible: true }
  const notched: Project = {
    ...project,
    stock: {
      ...project.stock,
      profile: polygonProfile([
        { x: 0, y: 0 }, { x: 100, y: 0 }, { x: 100, y: 80 }, { x: 40, y: 80 }, { x: 40, y: 50 }, { x: 0, y: 50 },
      ]),
    },
    tabs: [tab],
    clamps: [clamp],
  }
  const paths = generatePaths(notched)
  const bottom = bottomSetupOf(notched)
  const input = buildSimulationSetupInput(notched, bottom, paths)

  const frame = setupFrame(bottom.orientation, notched.stock)
  const turned = projectInSetupFrame(notched, frame)
  assertEqual(input.project.stock.profile, turned.stock.profile, 'the stock outline is the turned one')

  const toLocal = (point: Point): Point => {
    const mapped = canonicalToSetupPoint({ x: point.x, y: point.y, z: 0 }, frame)
    return { x: mapped.x, y: mapped.y }
  }
  const tabCorner = toLocal({ x: tab.x, y: tab.y + tab.h })
  assertEqual(
    { x: input.project.tabs[0].x, y: input.project.tabs[0].y, w: input.project.tabs[0].w, h: input.project.tabs[0].h },
    { x: tabCorner.x, y: tabCorner.y, w: tab.w, h: tab.h },
    'the tab is placed on the turned stock',
  )
  assertEqual(
    { top: input.project.tabs[0].z_top, bottom: input.project.tabs[0].z_bottom },
    { top: MM.thickness - tab.z_bottom, bottom: MM.thickness - tab.z_top },
    'and its Z span is reflected',
  )
  const clampCorner = toLocal({ x: clamp.x, y: clamp.y + clamp.h })
  assertEqual(
    { x: input.project.clamps[0].x, y: input.project.clamps[0].y, height: input.project.clamps[0].height },
    { x: clampCorner.x, y: clampCorner.y, height: clamp.height },
    'the clamp moves with the stock and keeps its height above the face that is up',
  )
  assert(input.project.origin === notched.origin, 'the shared origin is not turned')
}

// ── Run ───────────────────────────────────────────────────────

testTopIsTheSameObjects()
testDisabledAndHiddenOperationsAreIncluded()
testLegacyOperationsReadAsTop()
testBottomIsScopedAndTurned()
testProvisionalAndEmptyBottom()
testInvalidExplicitSetupThrows()
testFreshStockSimulation(MM)
testFreshStockSimulation(INCH)
testExportParity(MM)
testExportParity(INCH)
testDrillAndLevelMetadataPreserved()
testStockProfileTabsAndClampsAreTurned()

console.log('simulation setup input tests passed')
