/**
 * Copyright 2026 Franja (Frank) Povazanj
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * The simulation panel's setup wiring (issue #947): which setup is simulated,
 * and that `useSimulationModel` hands the unchanged heightfield engine that
 * setup's operations in its own frame, on fresh stock.
 *
 * The pockets are generated by the shipped generation path and simulated by
 * the shipped engine through the real hook, so a frame or scope the wiring
 * gets wrong shows up as material in the wrong place.
 *
 * Mutations these assertions were checked against, each applied on its own
 * and reverted:
 * - `useSimulationModel` simulating the canonical selected path instead of the
 *   setup input's → "the Bottom pocket is cut from the top of the flipped
 *   stock" fails;
 * - `resolveSimulationSetup` ignoring the selected operation → "selecting a
 *   Bottom operation simulates Bottom" fails;
 * - the acquisition asking for every prior operation regardless of setup →
 *   "Bottom playback is available" fails (it waits on a Top path);
 * - `simulationClamps` read from the canonical project → "the clamp sits
 *   where the turned stock puts it" fails.
 *
 * Run with: npx tsx src/app/simulationSetupModel.test.ts
 */

import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { computeOperationToolpath } from '../engine/toolpaths/generateOperation'
import type { ToolpathResult } from '../engine/toolpaths/types'
import type { SimulationGrid } from '../engine/simulation'
import { syncProjectSetups } from '../store/helpers/setups'
import { provisionalSetupId } from '../store/helpers/provisionalSetup'
import { BOTTOM_SETUP_ID, projectWithFeatures, withBottomSetup } from '../test/projectFixtures'
import {
  defaultTool, newProject, rectProfile, type Clamp, type Operation, type Project, type SetupFace, type SketchFeature,
} from '../types/project'
import { resolveSimulationSetup, simulationSetups } from './simulationSetup'
import { useSimulationModel } from './useSimulationModel'

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`Assertion failed: ${message}`)
}

// ── Fixture: Top pocket, Bottom pocket, flipped about X ───────

const STOCK = { x: 10, y: 5, w: 100, h: 80, t: 20 }
const DEPTH = 6
const TOP_RECT = { x: 20, y: 15, w: 24, h: 14 }
const BOTTOM_RECT = { x: 72, y: 32, w: 20, h: 16 }

function pocket(id: string, rect: typeof TOP_RECT, zTop: number, zBottom: number, face: SetupFace): SketchFeature {
  return {
    id, name: id, kind: 'rect', folderId: null,
    sketch: {
      profile: rectProfile(rect.x, rect.y, rect.w, rect.h),
      origin: { x: 0, y: 0 }, orientationAngle: 0, dimensions: [], constraints: [],
    },
    operation: 'subtract', z_top: zTop, z_bottom: zBottom, authoringFace: face, visible: true, locked: false,
  }
}

function operation(id: string, featureId: string, setupId: string): Operation {
  return {
    id, name: id, kind: 'pocket', pass: 'rough', enabled: true, showToolpath: true, debugToolpath: false,
    target: { source: 'features', featureIds: [featureId] }, toolRef: 't1', setupId,
    stepdown: DEPTH, stepover: 0.4, feed: 600, plungeFeed: 180, rpm: 18000,
    pocketPattern: 'offset', pocketAngle: 0, stockToLeaveRadial: 0, stockToLeaveAxial: 0,
    finishWalls: true, finishFloor: true, carveDepth: 2, maxCarveDepth: 2,
    cutDirection: 'conventional', machiningOrder: 'level_first',
  }
}

function makeProject(): Project {
  const base = newProject('sim-model', 'mm')
  base.meta = { ...base.meta, operationClearanceZ: 8 }
  base.stock = { ...base.stock, profile: rectProfile(STOCK.x, STOCK.y, STOCK.w, STOCK.h), thickness: STOCK.t }
  base.origin = { name: 'Origin', x: STOCK.x, y: STOCK.y + STOCK.h, z: STOCK.t, visible: true }
  base.tools = [{ ...defaultTool('mm', 1), id: 't1', name: 'Flat', diameter: 6, maxCutDepth: 40 }]
  const clamp: Clamp = { id: 'clamp-1', name: 'Clamp', type: 'step_clamp', x: 14, y: 8, w: 6, h: 4, height: 10, visible: true }
  base.clamps = [clamp]
  const withFeatures = projectWithFeatures(base, [
    pocket('top-pocket', TOP_RECT, STOCK.t, STOCK.t - DEPTH, 'top'),
    pocket('bottom-pocket', BOTTOM_RECT, DEPTH, 0, 'bottom'),
  ])
  const topId = withFeatures.activeSetupId
  const synced = syncProjectSetups({
    ...withFeatures,
    operations: [
      operation('opTop', 'top-pocket', topId),
      // A second Bottom-face operation listed after Top, so a playback that
      // replayed every prior operation would carry Top's cut into Bottom.
      operation('opBottom', 'bottom-pocket', topId),
    ],
  })
  return withBottomSetup(synced, { axis: 'x', operationIds: ['opBottom'] })
}

function generate(project: Project, id: string): ToolpathResult {
  const op = project.operations.find((entry) => entry.id === id)
  assert(op, `fixture: ${id} exists`)
  const envelope = computeOperationToolpath(project, op)
  assert(envelope, `fixture: ${id} is generated`)
  return envelope.result
}

function topZAt(grid: SimulationGrid, x: number, y: number): number {
  const col = Math.min(grid.cols - 1, Math.max(0, Math.floor((x - grid.originX) / grid.cellSize)))
  const row = Math.min(grid.rows - 1, Math.max(0, Math.floor((y - grid.originY) / grid.cellSize)))
  return grid.topZ[row * grid.cols + col]
}

/** Mirror about the stock's X axis line — literal arithmetic, not the engine's. */
function flipY(point: { x: number; y: number }): { x: number; y: number } {
  return { x: point.x, y: 2 * (STOCK.y + STOCK.h / 2) - point.y }
}

const centre = (rect: typeof TOP_RECT) => ({ x: rect.x + rect.w / 2, y: rect.y + rect.h / 2 })

type Args = Parameters<typeof useSimulationModel>[0]
type Result = ReturnType<typeof useSimulationModel>

function render(args: Args): Result {
  let captured: Result | null = null
  function Capture() {
    // eslint-disable-next-line react-hooks/globals
    captured = useSimulationModel(args)
    return null
  }
  renderToStaticMarkup(createElement(Capture))
  assert(captured, 'useSimulationModel rendered')
  return captured
}

function selectedArgs(project: Project, id: string, toolpath: ToolpathResult): Args {
  const selectedOperation = project.operations.find((entry) => entry.id === id) ?? null
  return {
    project, centerTab: 'simulation', simulationMode: 'selected', simulationDetailCells: 240,
    selectedOperation, selectedToolpath: toolpath, requestToolpath: () => Promise.resolve(null),
  }
}

// ── Which setup is simulated ──────────────────────────────────

function testResolution(): void {
  console.log('Testing which setup the simulation shows...')
  const project = makeProject()
  const top = project.setups[0]
  const opTop = project.operations[0]
  const opBottom = project.operations[1]
  const onTop: Project = { ...project, activeSetupId: top.id }
  const onBottom: Project = { ...project, activeSetupId: BOTTOM_SETUP_ID }

  assert(resolveSimulationSetup(onTop, null, null).id === top.id, 'with nothing selected it follows the workspace face (Top)')
  assert(resolveSimulationSetup(onBottom, null, null).id === BOTTOM_SETUP_ID, 'and (Bottom)')
  assert(resolveSimulationSetup(onTop, null, opBottom).id === BOTTOM_SETUP_ID, 'selecting a Bottom operation simulates Bottom')
  assert(resolveSimulationSetup(onBottom, null, opTop).id === top.id, 'selecting a Top operation simulates Top')
  assert(resolveSimulationSetup(onTop, BOTTOM_SETUP_ID, opTop).id === BOTTOM_SETUP_ID, 'an explicit pick wins')
  assert(resolveSimulationSetup(onTop, 'gone', null).id === top.id, 'a pick of a setup that no longer exists falls back')

  // A provisional Bottom the workspace looks at is a pickable, empty setup.
  const topOnly: Project = { ...project, setups: [top], operations: [opTop], activeSetupId: provisionalSetupId('bottom') }
  assert(
    JSON.stringify(simulationSetups(topOnly).map((setup) => setup.id)) === JSON.stringify([top.id, provisionalSetupId('bottom')]),
    'the provisional Bottom setup is listed after the project\'s own',
  )
  // A dangling setup reference does not take the choice down.
  const dangling: Project = { ...onTop, operations: [opTop, { ...opBottom, setupId: 'gone' }] }
  assert(resolveSimulationSetup(dangling, null, opBottom).id === top.id, 'a dangling reference falls back to the workspace face')
}

// ── The hook simulates the chosen setup in its frame ──────────

function testBottomSelectedSimulatesLocally(): void {
  console.log('Testing a selected Bottom operation is simulated from the top of the flipped stock...')
  const project = { ...makeProject(), activeSetupId: makeProject().setups[0].id }
  const bottomPath = generate(project, 'opBottom')
  const result = render(selectedArgs(project, 'opBottom', bottomPath))

  assert(result.simulationSetupPicker.selectedId === BOTTOM_SETUP_ID, 'selecting a Bottom operation simulates Bottom')
  assert(result.simulationSetupPicker.options.length === 2, 'the picker lists both setups')
  const grid = result.simulationResult?.grid
  assert(grid, 'a simulation result exists')
  const local = flipY(centre(BOTTOM_RECT))
  assert(
    topZAt(grid, local.x, local.y) < STOCK.t - DEPTH * 0.5,
    `the Bottom pocket is cut from the top of the flipped stock (Z ${topZAt(grid, local.x, local.y)} at its flipped centre)`,
  )
  const asDrawn = centre(BOTTOM_RECT)
  assert(Math.abs(topZAt(grid, asDrawn.x, asDrawn.y) - STOCK.t) < 1e-6, 'nothing is cut at the unflipped position')
  const topLocal = flipY(centre(TOP_RECT))
  assert(Math.abs(topZAt(grid, topLocal.x, topLocal.y) - STOCK.t) < 1e-6, 'Top\'s pocket is not on Bottom\'s fresh stock')

  const clamp = result.simulationClamps[0]
  const expected = flipY({ x: 14, y: 8 + 4 })
  assert(
    clamp && Math.abs(clamp.x - expected.x) < 1e-9 && Math.abs(clamp.y - expected.y) < 1e-9,
    `the clamp sits where the turned stock puts it (got ${JSON.stringify(clamp)})`,
  )

  // Playback runs the same local motion and starts from fresh stock: Top's
  // cut, listed before it, is not part of Bottom's starting state.
  const playback = result.simulationPlaybackInput
  assert(playback, 'Bottom playback is available')
  assert(playback.moves.every((move) => move.to.z <= STOCK.t + 8 + 1e-9), 'playback moves are setup-local, above the bed')
  assert(playback.moves.some((move) => move.kind === 'cut' && move.to.z > STOCK.t - DEPTH - 1e-9 && move.to.z < STOCK.t), 'and cut down from the top face')
  const base = playback.getBaseGrid()
  assert(Math.abs(topZAt(base, topLocal.x, topLocal.y) - STOCK.t) < 1e-6, 'Top\'s cut is not carried into Bottom playback')
}

function testTopIsUnchangedAndPickHolds(): void {
  console.log('Testing a Top selection simulates as before, and a pick lasts while the selection does...')
  const project = makeProject()
  const topPath = generate(project, 'opTop')
  const result = render(selectedArgs(project, 'opTop', topPath))
  assert(result.simulationSetupPicker.selectedId === project.setups[0].id, 'a Top operation simulates Top')
  const grid = result.simulationResult?.grid
  assert(grid, 'a simulation result exists')
  const at = centre(TOP_RECT)
  assert(topZAt(grid, at.x, at.y) < STOCK.t - DEPTH * 0.5, 'the Top pocket is cut where it is drawn')
  assert(result.simulationClamps[0].x === 14 && result.simulationClamps[0].y === 8, 'Top clamps are where they are drawn')
  assert(result.simulationOperationCount === 1, 'one operation is simulated')

  // Picking Bottom while Top's operation stays selected shows Bottom's empty
  // fresh stock: the Top operation is never simulated on the Bottom face.
  // (The pick is state; a static render cannot hold it, so read the rule.)
  const picked = resolveSimulationSetup(project, BOTTOM_SETUP_ID, project.operations[0])
  assert(picked.id === BOTTOM_SETUP_ID, 'the pick is honoured while the selection is unchanged')
}

function testSingleSetupHasNoPicker(): void {
  console.log('Testing a single-setup project offers no picker...')
  const project = makeProject()
  const single: Project = syncProjectSetups({ ...project, setups: [project.setups[0]], operations: [project.operations[0]] })
  const result = render(selectedArgs(single, 'opTop', generate(single, 'opTop')))
  assert(result.simulationSetupPicker.options.length === 1, 'one setup, one option: the panel hides the picker and its note')
}

testResolution()
testBottomSelectedSimulatesLocally()
testTopIsUnchangedAndPickHolds()
testSingleSetupHasNoPicker()

console.log('simulation setup model tests passed')
