/**
 * Copyright 2026 Franja (Frank) Povazanj
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Plasma corpus for the QtPlasmaC simulator check (issue #954).
 *
 * Three groups, all run the same way:
 *
 * - `REFERENCE_CASES` — hand-written programs in `fixtures/`, taken from the
 *   QtPlasmaC manual. They must pass. They prove the harness accepts a correct
 *   program, and they are the shape the plasma post output (#959) aims at.
 * - `NEGATIVE_CASES` — `fixtures/negative/`, each a reference program with one
 *   defect. They must be rejected, each for its own rule. This is the mutation
 *   check: if one of these passes, the harness is not checking that rule.
 * - `EXPORTED_CASES` — programs generated by the plasma exporter. Empty until
 *   #959 lands; see the comment on it for how to add them.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Expectation } from './verdict'

/** Which simulator configuration runs the case — the machine's units, not the program's. */
export type SimMachine = 'metric' | 'imperial'

export interface PlasmaCase {
  /** File-safe identifier, unique across the corpus. */
  name: string
  /** Why this case exists — printed alongside the result. */
  covers: string
  machine: SimMachine
  /** The program text. A function so an exported case is generated on demand. */
  program: () => string
  expect: Expectation
}

const FIXTURE_DIR = join(import.meta.dirname, 'fixtures')

function fixture(relativePath: string): () => string {
  return () => readFileSync(join(FIXTURE_DIR, relativePath), 'utf8')
}

export const REFERENCE_CASES: PlasmaCase[] = [
  {
    name: 'single-outline',
    covers: 'one closed outline: the minimum select-material / torch-on / cut / torch-off sequence',
    machine: 'metric',
    program: fixture('single-outline.ngc'),
    expect: 'pass',
  },
  {
    name: 'part-with-holes',
    covers: 'holes cut before the outline that frees the part; full-circle G3',
    machine: 'metric',
    program: fixture('part-with-holes.ngc'),
    expect: 'pass',
  },
  {
    name: 'nested-sheet',
    covers: 'several parts on one sheet: five pierces under one material select',
    machine: 'metric',
    program: fixture('nested-sheet.ngc'),
    expect: 'pass',
  },
  {
    name: 'arc-lead-ins',
    covers: 'G2/G3 lead-ins and lead-outs tangent to the cut, and arc corners',
    machine: 'metric',
    program: fixture('arc-lead-ins.ngc'),
    expect: 'pass',
  },
  {
    name: 'inch-output',
    covers: 'a G20 program on an inch machine',
    machine: 'imperial',
    program: fixture('inch-output.ngc'),
    expect: 'pass',
  },
  {
    name: 'inch-output-on-metric-machine',
    covers: 'the same G20 program on a metric machine, where the load filter converts units',
    machine: 'metric',
    program: fixture('inch-output.ngc'),
    expect: 'pass',
  },
]

export const NEGATIVE_CASES: PlasmaCase[] = [
  {
    name: 'cut-outside-torch',
    covers: 'a feed move after the torch-off: must be caught as cutting with no torch',
    machine: 'metric',
    program: fixture('negative/cut-outside-torch.ngc'),
    expect: { fails: 'torch' },
  },
  {
    name: 'missing-material-select',
    covers: 'no M190 before the first torch-on',
    machine: 'metric',
    program: fixture('negative/missing-material-select.ngc'),
    expect: { fails: 'material' },
  },
  {
    name: 'syntax-error',
    covers: 'an arc with no centre: must be caught as an interpreter error',
    machine: 'metric',
    program: fixture('negative/syntax-error.ngc'),
    expect: { fails: 'interpreter' },
  },
  {
    name: 'unknown-material',
    covers: "a material QtPlasmaC does not have: must be caught by QtPlasmaC's own load filter",
    machine: 'metric',
    program: fixture('negative/unknown-material.ngc'),
    expect: { fails: 'load' },
  },
]

/**
 * Programs produced by the plasma exporter — the plug-in point for #959.
 *
 * Add a case per export scenario, generated from the current exporter the same
 * way `../corpus.ts` generates the router corpus, so this always checks what
 * we emit today rather than a committed snapshot:
 *
 *   {
 *     name: 'exported-single-outline',
 *     covers: 'through-cut profile on one closed outline, QtPlasmaC definition',
 *     machine: 'metric',
 *     program: () => runPostProcessor({ project, definition, operations, options }).gcode,
 *     expect: 'pass',
 *   }
 *
 * Constraints the simulator imposes on an exported case:
 * - select material 1 or 2 (`sim/materials-*.cfg`); material 0 is reserved as
 *   "nothing selected" and fails the `material` rule by design;
 * - stay on the sim table, X/Y 0-1200 mm (0-48 in on the imperial machine);
 * - keep it small: the run is real time.
 *
 * Mirror each reference case above (outline, holes, nested sheet, arc
 * lead-ins, inch) so a difference between a reference program and its exported
 * twin is visible in one place.
 */
export const EXPORTED_CASES: PlasmaCase[] = []

export const PLASMA_CORPUS: PlasmaCase[] = [...REFERENCE_CASES, ...NEGATIVE_CASES, ...EXPORTED_CASES]
