/**
 * Copyright 2026 Franja (Frank) Povazanj
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Plasma corpus for the QtPlasmaC simulator check (issue #954).
 *
 * Four groups, all run the same way:
 *
 * - `REFERENCE_CASES` — hand-written programs in `fixtures/`, taken from the
 *   QtPlasmaC manual. They must pass. They prove the harness accepts a correct
 *   program, and they are the shape the plasma post output (#959) aims at.
 * - `NEGATIVE_CASES` — `fixtures/negative/`, each a reference program with one
 *   defect. They must be rejected, each for exactly its own rules. This is the
 *   mutation check: if one of these passes, or trips fewer rules than it
 *   should, the harness is not checking that rule.
 * - `EXPORTED_CASES` — programs generated by the plasma exporter (#959), each
 *   the twin of a reference case. They must pass.
 * - `HARNESS_CASES` — the harness checking itself in the real simulator.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Expectation } from './verdict'
import { exportPlasma, PLASMA_EXPORT_SCENARIOS } from '../../../src/test/plasmaExportFixtures'

/** Which simulator configuration runs the case — the machine's units, not the program's. */
export type SimMachine = 'metric' | 'imperial'

export interface PlasmaCase {
  /** File-safe identifier, unique across the corpus. */
  name: string
  /** Why this case exists — printed alongside the result. */
  covers: string
  machine: SimMachine
  /** The program text. A function so an exported case is generated on demand. */
  program: () => string
  expect: Expectation
  /**
   * Harness self-check only: have the driver sabotage this program's first
   * Cycle Start, and require that it took exactly `startAttempts` presses.
   */
  fault?: 'refused-start'
  startAttempts?: number
  /**
   * The program must make QtPlasmaC apply its automatic small-hole feed
   * reduction at run time. Set on the exported small-hole case; the header
   * alone (`#<holes> = 1`) is not evidence that the reduction happened.
   */
  expectHoleReduction?: boolean
}

const FIXTURE_DIR = join(import.meta.dirname, 'fixtures')

function fixture(relativePath: string): () => string {
  return () => readFileSync(join(FIXTURE_DIR, relativePath), 'utf8')
}

export const REFERENCE_CASES: PlasmaCase[] = [
  {
    name: 'single-outline',
    covers: 'one closed outline: the minimum select-material / torch-on / cut / torch-off sequence',
    machine: 'metric',
    program: fixture('single-outline.ngc'),
    expect: 'pass',
  },
  {
    name: 'part-with-holes',
    covers: 'holes cut before the outline that frees the part; full-circle G3',
    machine: 'metric',
    program: fixture('part-with-holes.ngc'),
    expect: 'pass',
  },
  {
    name: 'nested-sheet',
    covers: 'several parts on one sheet: four pierces under one material select',
    machine: 'metric',
    program: fixture('nested-sheet.ngc'),
    expect: 'pass',
  },
  {
    name: 'arc-lead-ins',
    covers: 'G2/G3 lead-ins and lead-outs tangent to the cut, and arc corners',
    machine: 'metric',
    program: fixture('arc-lead-ins.ngc'),
    expect: 'pass',
  },
  {
    name: 'inch-output',
    covers: 'a G20 program on an inch machine',
    machine: 'imperial',
    program: fixture('inch-output.ngc'),
    expect: 'pass',
  },
  {
    name: 'inch-output-on-metric-machine',
    covers: 'the same G20 program on a metric machine, where the load filter converts units',
    machine: 'metric',
    program: fixture('inch-output.ngc'),
    expect: 'pass',
  },
]

export const NEGATIVE_CASES: PlasmaCase[] = [
  {
    name: 'cut-outside-torch',
    covers: 'a feed move after the torch-off: must be caught as cutting with no torch',
    machine: 'metric',
    program: fixture('negative/cut-outside-torch.ngc'),
    expect: { fails: ['torch'] },
  },
  {
    name: 'missing-material-select',
    covers: 'no M190 before the first torch-on',
    machine: 'metric',
    program: fixture('negative/missing-material-select.ngc'),
    expect: { fails: ['material'] },
  },
  {
    name: 'missing-material-wait',
    covers: 'M190 with no M66 wait: the cut runs at the previous material\'s feed',
    machine: 'metric',
    program: fixture('negative/missing-material-wait.ngc'),
    expect: { fails: ['feed', 'material-wait'] },
  },
  {
    name: 'material-wait-after-feed',
    covers: 'the M66 wait placed after the feed word instead of before it',
    machine: 'metric',
    program: fixture('negative/material-wait-after-feed.ngc'),
    expect: { fails: ['feed', 'material-wait'] },
  },
  {
    name: 'syntax-error',
    covers: 'an arc with no centre: must be caught as an interpreter error',
    machine: 'metric',
    program: fixture('negative/syntax-error.ngc'),
    expect: { fails: ['interpreter'] },
  },
  {
    name: 'unknown-material',
    covers: "a material QtPlasmaC does not have: must be caught by QtPlasmaC's own load filter",
    machine: 'metric',
    program: fixture('negative/unknown-material.ngc'),
    expect: { fails: ['load'] },
  },
]

/**
 * Programs produced by the plasma exporter (#959), generated on demand from
 * the current exporter so this checks what we emit today rather than a
 * committed snapshot. Each is the exporter's program for the *subject* of the
 * reference case of the same name; the two are written independently, so a
 * contour count may differ and neither is a line-for-line copy of the other:
 *
 * - `nested-sheet`: the reference cuts three parts and a hole (four pierces),
 *   the exported scenario three plain parts (three pierces);
 * - `arc-lead-ins`: the reference is a rounded plate with a hole, the exported
 *   scenario a single disc;
 * - `inch-output`: the reference cuts a hole and an outline (two contours), the
 *   exported scenario a single outline;
 * - `small-hole` and `small-hole-arc-lead`: same 20 mm hole, straight leads and
 *   the default arc lead-in respectively;
 * - `single-outline` and `part-with-holes`: same subject and contour count as
 *   their reference.
 *
 * The scenarios live in `src/test/plasmaExportFixtures.ts`, where the unit
 * test (`src/engine/gcode/plasmaOutput.test.ts`) exports the same projects.
 *
 * Constraints the simulator imposes, which the scenarios keep:
 * - material 1 or 2 (`sim/materials-*.cfg`); material 0 is reserved as
 *   "nothing selected" and fails the `material` rule by design, while the
 *   exporter also refuses 1000000+ (QtPlasmaC's temporary-material range);
 * - X/Y within 0-1200 mm (0-48 in on the imperial machine);
 * - small, because the run is real time.
 */
const exported = (
  name: string,
  machine: SimMachine,
  covers: string,
  options: { expectHoleReduction?: boolean } = {},
): PlasmaCase => ({
  name: `exported-${name}${machine === 'metric' && name === 'inch-output' ? '-on-metric-machine' : ''}`,
  covers: `exported program for the ${name} subject: ${covers}`,
  machine,
  program: () => {
    const { result } = exportPlasma(PLASMA_EXPORT_SCENARIOS[name]())
    if (result.warnings.length > 0) {
      throw new Error(`exported case ${name} raised ${result.warnings.map((warning) => warning.code).join(', ')}`)
    }
    return result.gcode
  },
  expect: 'pass',
  ...options,
})

export const EXPORTED_CASES: PlasmaCase[] = [
  exported('single-outline', 'metric', 'one outline, arc lead-in and line lead-out from #957'),
  exported('part-with-holes', 'metric', 'two holes before the outline, arc-fitted circles'),
  exported('nested-sheet', 'metric', 'three parts, three pierces under one material select'),
  exported('arc-lead-ins', 'metric', 'a disc with arc lead-in and arc lead-out'),
  exported('small-hole', 'metric', 'a 20 mm hole with straight leads, which QtPlasmaC must reduce to 60% of the cut feed', { expectHoleReduction: true }),
  exported('small-hole-arc-lead', 'metric', 'the same 20 mm hole with the default arc lead-in, which QtPlasmaC must also reduce to 60%', { expectHoleReduction: true }),
  exported('inch-output', 'imperial', 'a G20 program on an inch machine'),
  exported('inch-output', 'metric', 'the same G20 program on a metric machine'),
]

/**
 * Checks of the harness itself, run in the real simulator alongside the corpus.
 *
 * `refused-cycle-start` is the regression for a start that never happened
 * going unnoticed (#954). The driver puts LinuxCNC back in manual mode just
 * before the first Cycle Start, the way the QtPlasmaC GUI can, and changes the
 * material so the trace shows a feed change with nothing running. The driver
 * must notice the refusal and press again: two presses, and then a correct
 * program must still pass. One press means the refusal was mistaken for a
 * start.
 */
export const HARNESS_CASES: PlasmaCase[] = [
  {
    name: 'refused-cycle-start',
    covers: 'harness self-check: a refused Cycle Start is noticed and repeated, not taken for a run',
    machine: 'metric',
    program: fixture('single-outline.ngc'),
    expect: 'pass',
    fault: 'refused-start',
    startAttempts: 2,
  },
]

export const PLASMA_CORPUS: PlasmaCase[] = [
  ...REFERENCE_CASES, ...NEGATIVE_CASES, ...EXPORTED_CASES, ...HARNESS_CASES,
]
